### ISSUE TITLE
prototype vscode editor for lexicon files

### ISSUE THREAD

**Issue by arrocke** [globalbibletools/lexicon-translation#1]
We want to build a prototype editor view as a vscode extension for editing lexicon entry xml files. The extension should load a custom editor to edit XML files in the globalbibletools/semantic-dictionary repository.

**Comment by Pertempto** [comment]
Questions to clarify my understanding...

- The only example XML file right now is [000001.xml](https://github.com/globalbibletools/semantic-dictionary/blob/main/data/eng/000001.xml)?
- Eventually we will have a bunch of other XML files to load and support?
  - I'm guessing they will be of the same format as the existing one?

**Comment by Pertempto** [comment]
@arrocke can you initialize the git repo for this one with at least something? GitHub doesn't seem to allow me to push a branch.

**Comment by Pertempto** [comment]
Or maybe it is an access rights problem.

```
git push --set-upstream origin prototype-addison
remote: Permission to globalbibletools/lexicon-translation.git denied to Pertempto.
fatal: unable to access 'https://github.com/globalbibletools/lexicon-translation.git/': The requested URL returned error: 403
```

**Comment by arrocke** [comment]
Ok, I think I fixed the permission issue

**Comment by Pertempto** [comment]
The idea is to allow the user to edit any of the fields in the XML file, correct?

Still very early, but I've made a bit of progress.

![image](https://github.com/globalbibletools/lexicon-translation/assets/17209828/4abdf287-6ea7-4f5a-9d5e-c3e5ca9f0a81)

**Comment by arrocke** [comment]
Probably not every field needs to be editable. Only things that would be rendered in a UI in a given language need to be translated. So things like IDs, contributor names, URLs, strongs numbers, etc would not be editable. If somebody wants to do an analysis of the schema and make a recommendation for which fields should be translated, that would be a great starting point

**Comment by Pertempto** [comment]
I added comments with the fields I thought might need translating.

<details>
<summary>JSON version of `000001.xml`</summary>


```js
{
  "Lexicon_Entry": {
    "StrongCodes": {
      "Strong": [
        "H0003",
        "A0004"
      ]
    },
    "Authors": {
      "Author": "Reinier de Blois"
    },
    "Contributors": "",
    "AlternateLemmas": "",
    "MainLinks": "",
    "Notes": "", // Translate
    "ContributorNote": "", // Translate
    "BaseForms": {
      "BaseForm": {
        "PartsOfSpeech": {
          "PartOfSpeech": "nsm"
        },
        "RelatedLemmas": {
          "RelatedLemma": {
            "Word": "" // Not sure
          }
        },
        "BaseFormLinks": "",
        "LEXMeanings": {
          "LEXMeaning": [
            {
              "LEXDomains": {
                "LEXDomain": "Vegetation" // Translate
              },
              "LEXSenses": {
                "LEXSense": {
                  "DefinitionLong": "", // Translate
                  "DefinitionShort": "= part of a plant or tree that is typically surrounded by brightly colored petals and will eventually develop into a fruit", // Translate
                  "Glosses": {
                    "Gloss": [ // Translate
                      "blossom",
                      "flower"
                    ]
                  },
                  "Comments": "" // Translate
                }
              },
              "LEXReferences": {
                "LEXReference": 2200601100016
              },
              "LEXVideos": "",
              "LEXCoreDomains": {
                "LEXCoreDomain": "Plant" // Translate
              }
            },
            {
              "LEXDomains": {
                "LEXDomain": "Stage" // Translate
              },
              "LEXCollocations": {
                "LEXCollocation": "בְּאֵב"
              }
            }
          ],
          "LEXSenses": {
            "LEXSense": {
              "DefinitionLong": "", // Translate
              "DefinitionShort": "= state in which a plant or tree has developed blossoms", // Translate
              "Glosses": {
                "Gloss": "blossom" // Translate
              },
              "Comments": "" // Translate
            }
          },
          "LEXReferences": {
            "LEXReference": 1800801200006
          },
          "LEXVideos": "",
          "LEXCoreDomains": {
            "LEXCoreDomain": "Plant" // Translate
          }
        },
        "LEXMeaning": {
          "LEXDomains": {
            "LEXDomain": "Fruits" // Translate
          },
          "LEXSenses": {
            "LEXSense": {
              "DefinitionLong": "", // Translate
              "DefinitionShort": "= part of a plant or tree that carries the seed and is often edible", // Translate
              "Glosses": {
                "Gloss": "fruit" // Translate
              },
              "Comments": "" // Translate
            }
          },
          "LEXReferences": {
            "LEXReference": [
              2700400900008,
              2700401100032,
              2700401800010
            ]
          },
          "LEXVideos": "",
          "LEXCoreDomains": {
            "LEXCoreDomain": "Plant" // Translate
          }
        }
      }
    }
  }
}
```

</details>


It seems like these are the keys to look out for, no matter where they appear nested

- `Notes`
- `ContributorNote`
- `DefinitionLong`
- `DefinitionShort`
- `Gloss`
- `LEXCoreDomain`
- `LEXDomain`

**Comment by Pertempto** [comment]
Useful document - https://docs.google.com/document/d/1K1KATgH7Dn5whr3tLBSR4Y0NIqUbw9nWUt9jpYGVgF0/

**Comment by arrocke** [comment]
I took a look at the fields you identified, and it seems like LEXCoreDomain and LEXDomain come from [this XML file](https://github.com/ubsicap/ubs-open-license/blob/main/dictionaries/hebrew/XML/UBSHebrewDicLexicalDomains-v0.9.1-en.XML), that we will translate as well. My guess is that we can translate that file and then use that data to replace them where they are used in every word.

I'm going to suggest that for the prototype, especially while we are trying to figure out this vscode stuff, we focus on the definitions and the glosses. We'll need to figure out how to connect to the lexical domain data set next, but one thing at a time

**Comment by arrocke** [comment]
Here is what I'm thinking we need to demonstrate in this prototype. I'm curious what others think.

* Translator can translate common words like parts of speech and book names that will be used everywhere in the lexicon
* Translator can view and edit translatable text in the entry for each word, and lexical domain
* Translator can preview an entry for a word or lexical domain in either an available source language or the target language they are working on.
* Translator can send their progress to a remote git server for review
* Translator can compare other's work with their own, and can choose what to take and what to ignore

It may also be useful to see how we can integrate with work that others are doing in vscode:

* verse translation preview
* comments
* copilot like AI, but for translating

**Comment by arrocke** [comment]
Closing this now in favor of #2
